# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048 
    v.cpus = 2
  end

  config.vm.provision "shell", inline: <<-SHELL
     sudo dpkg --add-architecture i386
     sudo apt-get update
     cd /home/vagrant
     curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
     sudo apt-get install -y nodejs
     sudo apt-get install -y build-essential gcc-multilib git lib32stdc++-4.8-dev lib32z1-dev python-dev python3-dev zlib1g-dev
  SHELL
end
